### ISSUE TITLE
Investigate `ms-stream` for IE.

### ISSUE THREAD

**Issue by jonnyreeves** [jonnyreeves/chunked-request#10]
https://msdn.microsoft.com/en-us/library/hh772328(v=vs.85).aspx

**Comment by ariutta** [comment]
The `requests` (plural) library [uses ms-stream](https://github.com/unshiftio/requests/blob/87d2fa137d512e2a47aa7eb9e1395f2059720299/browser.js#L139). It even supports [using ActiveX](https://github.com/unshiftio/requests/blob/87d2fa137d512e2a47aa7eb9e1395f2059720299/browser.js#L193) for old versions of IE. Could you start with that implementation?

**Comment by ariutta** [comment]
I've got a rough `ms-stream` implementation [here](https://github.com/ariutta/chunked-request/blob/e8e354d1f018f53f154b3b0ce8ef2593dda39329/src/defaultTransportFactory.js#L85) in the `ms-stream` branch of my fork.

**Comment by ariutta** [comment]
~~I'll work on merging my `ms-stream` implementation into your latest feature code.~~ (Actually, I'll wait until you can merge our latest work into master.) ~~Any thoughts on the abstraction for streaming `xhr`? If I make a version to work with IE10+ and possible IE9, I don't know whether it's ideal to make another file named msXhr.js, because there will be quite a bit of code shared between xhr.js, mozXhr.js and msXhr.js. I could pull out the common code and only include it once.~~ (We've [decided](https://github.com/jonnyreeves/chunked-request/pull/15#issuecomment-241338965) to dedup the common code between XHR implementations.)

**Comment by ariutta** [comment]
[This comment](https://github.com/jonnyreeves/chunked-request/issues/16#issuecomment-241537946) is relevant to the question of how to make an abstraction that works with the IE `ms-stream` `readAsArrayBuffer` method.

**Comment by jonnyreeves** [comment]
See https://github.com/jhiesey/stream-http/blob/master/lib/response.js#L157 - got a little disheartened when I first came across this library as it somewhat fulfils my original needs when writing this one! 😁  - however it would appear this one is turning into a slightly more modern interface which may prove useful for some.

**Comment by jonnyreeves** [comment]
Opened as https://github.com/jonnyreeves/fetch-readablestream/issues/1
